// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esbniqtvjywnlzfabwoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzYm5pcXR2anl3bmx6ZmFid29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTQ3NjQsImV4cCI6MjA3MDYzMDc2NH0.xPC1hpQvldjhEVtO-YpOUWnw-z_1M-u6HJhLlOIRZgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});